### ISSUE TITLE
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle ... is required.

### ISSUE THREAD

**Issue by lolkekabcqqq** [myTrackerSDK/mytracker-ios#5]
Hello! You have a problem like some other frameworks. For example, Firebase. Could you please fix it?
https://github.com/firebase/firebase-ios-sdk/issues/12441

**Comment by aserrr** [comment]
Hi,
There is an issue in Xcode 15.3 I believe.
Please use 15.2 or 15.4 version for app distribution.

**Comment by imurashov-belkacar** [comment]
Same with Xcode 15.4.
I cannot upload build to AppStore Connect because ` Asset validation failed Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'Frameworks/GoogleAppMeasurementIdentitySupport.framework' is ''. (ID: 21bf50fb-9e30-46a9-b40a-1e8386835622) (90530)`

**Comment by aserrr** [comment]
This looks like an issue in GoogleAppMeasurement framework

**Comment by imurashov-belkacar** [comment]
@aserrr Thanks, that's true.
Some versions of Google's packages are incompatible with Xcode 15.4. In my case the problem was with firebase package dependencies. Latest version of Firebase works fine.
